## Loop process with error catch event

This is a very simple test used to test loops and error catch event. The service named `Throw BpmnError` will throw a BpmnError that will be catch in the sub process by the Error Start event. The fact that this service is in a loop creates a SQL error 

	org.apache.ibatis.exceptions.PersistenceException: 
	### Error updating database.  Cause: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "ACT_FK_VAR_EXE: PUBLIC.ACT_RU_VARIABLE FOREIGN KEY(EXECUTION_ID_) REFERENCES PUBLIC.ACT_RU_EXECUTION(ID_) ('8c358242-937d-11e5-9abb-e8b1fcf6cf02')"; SQL statement:
	insert into ACT_RU_VARIABLE (ID_, REV_,
	    TYPE_, NAME_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, BYTEARRAY_ID_,
	    DOUBLE_, LONG_ , TEXT_, TEXT2_)
	    values (
	    ?,
	    1,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?
	    ) [23506-187]
	### The error may involve org.activiti.engine.impl.persistence.entity.VariableInstanceEntity.insertVariableInstance-Inline
	### The error occurred while setting parameters
	### SQL: insert into ACT_RU_VARIABLE (ID_, REV_,     TYPE_, NAME_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, BYTEARRAY_ID_,     DOUBLE_, LONG_ , TEXT_, TEXT2_)     values (     ?,     1,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?     )
	### Cause: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "ACT_FK_VAR_EXE: PUBLIC.ACT_RU_VARIABLE FOREIGN KEY(EXECUTION_ID_) REFERENCES PUBLIC.ACT_RU_EXECUTION(ID_) ('8c358242-937d-11e5-9abb-e8b1fcf6cf02')"; SQL statement:
	insert into ACT_RU_VARIABLE (ID_, REV_,
	    TYPE_, NAME_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, BYTEARRAY_ID_,
	    DOUBLE_, LONG_ , TEXT_, TEXT2_)
	    values (
	    ?,
	    1,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?
	    ) [23506-187]
		at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
		at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150)
		at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:137)
		at org.activiti.engine.impl.db.DbSqlSession.flushRegularInsert(DbSqlSession.java:825)
		at org.activiti.engine.impl.db.DbSqlSession.flushPersistentObjects(DbSqlSession.java:805)
		at org.activiti.engine.impl.db.DbSqlSession.flushInserts(DbSqlSession.java:789)
		at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:610)
		at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:211)
		at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:137)
		at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:66)
		at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
		at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
		at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
		at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
		at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
		at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
		at org.activiti.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:69)
		at com.log10solutions.modulus.commons.process.test.RetryServiceErrorTest.testComplexRedoTask(RetryServiceErrorTest.java:113)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
		at org.activiti.engine.test.ActivitiRule$1.evaluate(ActivitiRule.java:126)
		at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
		at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
		at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
	Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "ACT_FK_VAR_EXE: PUBLIC.ACT_RU_VARIABLE FOREIGN KEY(EXECUTION_ID_) REFERENCES PUBLIC.ACT_RU_EXECUTION(ID_) ('8c358242-937d-11e5-9abb-e8b1fcf6cf02')"; SQL statement:
	insert into ACT_RU_VARIABLE (ID_, REV_,
	    TYPE_, NAME_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, BYTEARRAY_ID_,
	    DOUBLE_, LONG_ , TEXT_, TEXT2_)
	    values (
	    ?,
	    1,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?,
	    ?
	    ) [23506-187]
		at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
		at org.h2.message.DbException.get(DbException.java:179)
		at org.h2.message.DbException.get(DbException.java:155)
		at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:372)
		at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:314)
		at org.h2.table.Table.fireConstraints(Table.java:920)
		at org.h2.table.Table.fireAfterRow(Table.java:938)
		at org.h2.command.dml.Insert.insertRows(Insert.java:161)
		at org.h2.command.dml.Insert.update(Insert.java:114)
		at org.h2.command.CommandContainer.update(CommandContainer.java:78)
		at org.h2.command.Command.executeUpdate(Command.java:254)
		at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:198)
		at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41)
		at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66)
		at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45)
		at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
		at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
		at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
		... 50 more

Not sure why or how to fix ... if this is a true bug.